# Load and if necessary install packages
# install.packages('remotes')
remotes::install_github("statnet/statnet.common")

remotes::install_cran('renv')
remotes::install_cran('rmarkdown')
remotes::install_cran('tinytex')
remotes::install_cran('shiny')
remotes::install_cran('dplyr')
remotes::install_cran('DT')
remotes::install_cran('ggplot2')
remotes::install_cran('statnet')
remotes::install_cran('igraph')
remotes::install_cran('network')
remotes::install_cran('shinydashboard')
remotes::install_cran('shinyjs')
remotes::install_cran('plotly')
remotes::install_cran('magrittr')
remotes::install_cran('SimInf')
remotes::install_cran('data.table')
remotes::install_cran('shinyWidgets')
remotes::install_cran('dipsaus')
remotes::install_cran('shinyhelper')
remotes::install_cran('shinyTime')
remotes::install_cran('shinyalert')
remotes::install_cran('knitr')

remotes::install_github("MESuRS-Lab/mwss", quiet = T)

library('rmarkdown')
library('tinytex')
library('shiny')
library('dplyr')
library('DT')
library('ggplot2')
library('statnet')
library('igraph')
library('network')
library('shinydashboard')
library('shinyjs')
library('plotly')
library('magrittr')
library('SimInf')
library('data.table')
library('shinyWidgets')
library('dipsaus')
library('shinyhelper')
library('shinyTime')
library('shinyalert')
library('knitr')
library('mwss')

# Parameters dataset

#### Source function
source('functions/buttonsUI.R', local = TRUE)

source('functions/wardEditModule.R', local = TRUE)
source('functions/wardRemoveModule.R', local = TRUE)
source('functions/wardAdd.R', local = TRUE)
source('functions/contactEdit.R', local = TRUE)
source('functions/updateImportationLevel.R', local = TRUE)
source('functions/updateParamsModule.R', local = TRUE)
source('functions/downloadParamsModule.R', local = TRUE)
source('functions/setIMMstateModule.R', local = TRUE)
source('functions/diseasetimelineModule.R', local = TRUE)
source('functions/valueboxoutputModule.R', local = TRUE)
source('functions/plotsoutputModule.R', local = TRUE)
source('functions/resetreactivesModule.R', local = TRUE)
source('functions/exporttrajModule.R', local = TRUE)
source('functions/loadTestdtModule.R', local = TRUE)
source('functions/timeinputinday.R', local = TRUE)
source('functions/plot_networkModule.R', local = TRUE)
# source('functions/update_matContact_adv.R', local = TRUE)



# App Structure function

source('body/presentation.R', local = TRUE)
# source('body/initialization/tabItemInitialization.R', local = TRUE)
# source('body/parameters/tabItemParams.R', local = TRUE)
source('body/simulations/tabItemSimulation.R', local = TRUE)
source('body/simulations/simpleMode.R', local = TRUE)
source('body/simulations/advancedMode.R', local = TRUE)

# source('body/simulations/tabItemAdvMode.R', local = TRUE)
source('body/about.R', local = TRUE)

source('header/header_ui.R', local = TRUE)
source('body/sidebar_ui.R', local = TRUE)
source('body/body_ui.R', local = TRUE)

